#!/usr/bin/python
# -*- coding: utf-8 -*-
import logging
import logging.config

####### Static Constants and Configuration Items ########################
#Twitter Api Related constants
CONSUMER_KEY = 'XXXXXXXXXXXXXXXXX'
CONSUMER_SECRET = 'XXXXXXXXXXXXXXXXX'
ACCESS_TOKEN = 'XXXXXXXXXXXXXXXXX'
ACCESS_SECRET = 'XXXXXXXXXXXXXXXXX'

#itü nlp api login credentials
ITU_NLP_API_TOKEN = "XXXXXXXXXXXXXXXXX"

PIPELINE_ENCODING = 'UTF-8'
DEFAULT_TOOL = "normalize"
API_URL = 'http://tools.nlp.itu.edu.tr/SimpleApi'

STRING_VECTOR = {
    "Türkiye",
    "ABD",
    "Amerika Birleşik Devletleri",
    "Afganistan",
    "Almanya",
    "Andora",
    "Angola",
    "Anguilla",
    "Antarktika",
    "Barbuda",
    "Arjantin",
    "Arnavutluk",
    "Aruba",
    "Avrupa Birliği",
    "Avustralya",
    "Avusturya",
    "Azerbaycan",
    "Bahamalar",
    "Bahreyn",
    "Bangladeş",
    "Barbados",
    "Belçika",
    "Benin",
    "Beyaz Rusya",
    "Bermuda",
    "Bhutan",
    "Birleşik Arap Emirlikleri",
    "Birleşik Krallık",
    "Bolivya",
    "Bosna Hersek",
    "Botsvana",
    "Bouvet",
    "Brezilya",
    "Brunei",
    "Bulgaristan",
    "Burkina",
    "Burundi",
    "Cape Verde",
    "Cebelitarık",
    "Cezayir",
    "Cibuti",
    "Çad",
    "Çek Cumhuriyeti",
    "Çin",
    "Danimarka",
    "Dominik Cumhuriyeti",
    "Salvador",
    "Endonezya",
    "Ermenistan",
    "Estonya",
    "Etiyopya",
    "Fas",
    "Fiji",
    "Fildişi Sahilleri",
    "Filipinler",
    "Filistin",
    "Finlandiya",
    "Fransa",
    "Gabon",
    "Gambia",
    "Gana",
    "Gine-Bissau",
    "Granada",
    "Grönland",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guyana",
    "Güney Afrika",
    "Güney Kore",
    "Gürcistan",
    "Haiti",
    "Hindistan",
    "Hollanda",
    "Honduras",
    "Hong",
    "Hırvatistan",
    "Irak",
    "İngiltere",
    "İran",
    "İrlanda",
    "İspanya",
    "İsrail",
    "İsveç",
    "İsviçre",
    "İtalya",
    "İzlanda",
    "Jamaika",
    "Japonya",
    "Jersey",
    "Kamboçya",
    "Kamerun",
    "Kanada",
    "Karadağ",
    "Katar",
    "Kayman",
    "Kazakistan",
    "Kenya",
    "Kiribati",
    "Kolombiya",
    "Komorlar",
    "Kongo",
    "Kosta Rika",
    "Kuveyt",
    "Kuzey Kore",
    "Küba",
    "Kırgızistan",
    "Laos",
    "Lesotho",
    "Letonya",
    "Liberya",
    "Libya",
    "Liechtenstein",
    "Litvanya",
    "Lübnan",
    "Lüksemburg",
    "Macaristan",
    "Madagaskar",
    "Çin",
    "Makedonya",
    "Malavi",
    "Maldivler",
    "Malezya",
    "Mali",
    "Malta",
    "Meksika",
    "Mikronezya",
    "Moldovya",
    "Monako",
    "Montserrat",
    "Moritanya",
    "Mozambik",
    "Moğolistan",
    "Myanmar",
    "Mısır",
    "Namibya",
    "Nauru",
    "Nepal",
    "Nijer",
    "Nijerya",
    "Nikaragua",
    "Niue",
    "Norveç",
    "Afrika",
    "Özbekistan",
    "Pakistan",
    "Palau",
    "Panama",
    "Paraguay",
    "Peru",
    "Pitcairn",
    "Polonya",
    "Portekiz",
    "Porto Riko",
    "Reunion",
    "Romanya",
    "Ruanda",
    "Rusya",
    "Samoa",
    "Senegal",
    "Seyşeller",
    "Sierra Leone",
    "Singapur",
    "Slovakya",
    "Slovenya",
    "Somali",
    "Sri Lanka",
    "Sudan",
    "Surinam",
    "Suriye",
    "Arabistan",
    "Svaziland",
    "Sırbistan",
    "Sırbistan-Karadağ",
    "Şili",
    "Tacikistan",
    "Tanzanya",
    "Tayland",
    "Tayvan",
    "Togo",
    "Tokelau",
    "Tonga",
    "Tunus",
    "Tuvalu",
    "Türkmenistan",
    "Uganda",
    "Ukrayna",
    "Umman",
    "Uruguay",
    "Ürdün",
    "Vanuatu",
    "Vatikan",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Yunanistan",
    "Zambiya",
    "Zimbabve"

    "Adalet Bakanlığı",
    "Adıyaman Üniversitesi",
    "Adli Sicil ve İstatistik Genel Müdürlüğü",
    "Adli Tıp Kurumu Başkanlığı",
    "Afet ve Acil Durum Yönetimi Başkanlığı",
    "Ağrı İbrahim Çeçen Üniversitesi",
    "Ahmet Yesevi Üniversitesi",
    "Aile ve Sosyal Politikalar Bakanlığı",
    "Aile ve Toplum Hizmetleri Genel Müdürlüğü",
    "Akaryakıt İkmal ve Nato Pol Tesisleri İşletme",
    "ANT",
    "Amelebirliği",
    "Anadolu Ajansı Genel Müdürlüğü",
    "Anadolu Üniversitesi",
    "Anayasa Mahkemesi Başkanlığı",
    "Ankara Ticaret Odası",
    "Antalya Bilim Üniversitesi",
    "Artvin Çoruh Üniversitesi",
    "Asker Alma Dairesi Başkanlığı",
    "Askerî Yargıtay Başkanlığı",
    "Askerî Yüksek İdare Mahkemesi",
    "Ataşehir Adıgüzel Meslek Yüksekokulu",
    "Atatürk Araştırma Merkezi",
    "Atatürk Kültür, Dil ve Tarih Yüksek Kurumu Başkanlığı",
    "Atatürk Kültür Merkezi",
    "Atatürk Orman Çiftliği",
    "AB Bakanlığı",
    "Avrupa Birliği Eğitim ve Gençlik Programları Merkezi Başkanlığı",
    "Avrupa Birliği ve Dış İlişkiler Genel Müdürlüğü",
    "Balıkçılık ve Su ürünleri Genel Müdürlüğü",
    "Bandırma Onyedi Eylül üniversitesi",
    "Bankacılık Düzenleme ve Denetleme Kurumu",
    "Basın İlan Kurumu",
    "Basın Yayın ve Enformasyon Genel Müdürlüğü",
    "Başbakanlık",
    "Başbakanlık Güvenlik İşleri Genel Müdürlüğü",
    "Başbakanlık İdareyi Geliştirme Başkanlığı",
    "Batman Üniversitesi",
    "Bilgi Teknolojileri ve İletişim Kurumu",
    "Bilim, Sanayi ve Teknoloji Bakanlığı",
    "Bingöl Üniversitesi",
    "Bitkisel Üretim Genel Müdürlüğü",
    "Bitlis Eren Üniversitesi",
    "Boru Hatları İle Petrol Taşıma A.Ş.",
    "Bursa Teknik Üniversitesi",
    "Bütçe ve Mali Kontrol Genel Müdürlüğü",
    "Ceza İşleri Genel Müdürlüğü",
    "Ceza ve Tevkifevleri Genel Müdürlüğü",
    "Coğrafi Bilgi Sistemleri Genel Müdürlüğü",
    "Cumhurbaşkanlığı",
    "Çalışma Genel Müdürlüğü",
    "Çalışma ve Sosyal Güvenlik Bakanlığı",
    "Çalışma ve Sosyal Güvenlik Eğitim ve Araştırma Merkezi",
    "ÇASGEM",
    "Çanakkale Onsekiz Mart Üniversitesi",
    "Çay İşletmeleri Genel Müdürlüğü",
    "Çevresel Etki Değerlendirmesi, İzin ve Denetim Genel Müdürlüğü",
    "Çevre ve Şehircilik Bakanlığı",
    "Çevre Yönetimi Genel Müdürlüğü",
    "Çocuk Hizmetleri Genel Müdürlüğü",
    "Çölleşme ve Erozyonla Mücadele Genel Müdürlüğü",
    "Danıştay",
    "Dernekler Dairesi Başkanlığı",
    "Devlet Arşivleri Genel Müdürlüğü",
    "Devlet Hava Meydanları İşletmesi Genel Müdürlüğü",
    "Devlet Malzeme Ofisi Genel Müdürlüğü",
    "Devlet Opera ve Balesi Genel Müdürlüğü",
    "Devlet Personel Başkanlığı",
    "Devlet Su İşleri Genel Müdürlüğü",
    "Devlet Tiyatroları Genel Müdürlüğü",
    "Dış İlişkiler ve Yurt Dışı İşçi Hizmetleri Genel Müdürlüğü",
    "Dışişleri Bakanlığı",
    "Din Öğretimi Genel Müdürlüğü",
    "Diyanet İşleri Başkanlığı",
    "DLH İnşaatı Genel Müdürlüğü",
    "Doğa Koruma ve Millî Parklar Genel Müdürlüğü",
    "Doğal Afet Sigortaları Kurumu",
    "Ege Üniversitesi",
    "Ekonomi Bakanlığı",
    "Elektrik İşleri Etüt İdaresi Genel Müdürlüğü",
    "Elektrik Üretim A.Ş. Genel Müdürlüğü",
    "Emeklilik Gözetim Merkezi",
    "Emniyet Genel Müdürlüğü",
    "Enerji Piyasaları İşletme A.Ş.",
    "Enerji Piyasası Düzenleme Kurumu Başkanlığı",
    "Enerji ve Tabii Kaynaklar Bakanlığı",
    "Engelli ve Yaşlı Hizmetleri Genel Müdürlüğü",
    "Erişim Sağlayıcıları Birliği",
    "Esnaf ve Sanatkarlar Genel Müdürlüğü",
    "Eti Maden İşletmeleri Genel Müdürlüğü",
    "Et ve Süt Kurumu Genel Müdürlüğü",
    "Fatih Sultan Mehmet Üniversitesi",
    "Fırat Üniversitesi",
    "Finansal Kurumlar Birliği",
    "Futbol Federasyonu Başkanlığı",
    "Gaziosmanpaşa Üniversitesi",
    "Gelir İdaresi Başkanlığı",
    "Gelir Politikaları Genel Müdürlüğü",
    "Gençlik ve Spor Bakanlığı",
    "Genelkurmay Başkanlığı",
    "Gıda, Tarım ve  Hayvancılık Bakanlığı",
    "Gıda, Tarım ve Hayvancılık Bakanlığı Personel Genel Müdürlüğü",
    "Gıda ve Kontrol Genel Müdürlüğü",
    "Giresun Üniversitesi",
    "Göç İdaresi Genel Müdürlüğü",
    "Gümrük ve Ticaret Bakanlığı",
    "Gümüşhane Üniversitesi",
    "Güneydoğu Anadolu Projesi Bölge Kalkınma İdaresi Başkanlığı",
    "Güzel Sanatlar Genel Müdürlüğü",
    "Haberleşme Genel Müdürlüğü",
    "Harita Genel Komutanlığı",
    "Harran Üniversitesi",
    "Hayat Boyu Öğrenme Genel Müdürlüğü",
    "Hayvancılık Genel Müdürlüğü",
    "Hazine Müsteşarlığı",
    "Hitit Üniversitesi",
    "İçişleri Bakanlığı",
    "İç Ticaret Genel Müdürlüğü",
    "İlaç ve Eczacılık Genel Müdürlüğü",
    "İlksan",
    "İller Bankası A.Ş.",
    "İller İdaresi Genel Müdürlüğü",
    "İnsan Hakları Başkanlığı",
    "İnşaat Emlâk ve Nato Enfrastrüktür Dairesi Başkanlığı",
    "İskenderun Teknik Üniversitesi",
    "İstanbul Gedik Üniversitesi",
    "İstanbul Teknik Üniversitesi",
    "İŞKUR",
    "İş Sağlığı ve Güvenliği Genel Müdürlüğü",
    "Jandarma Genel Komutanlığı",
    "Jandarma ve Sahil Güvenlik Akademisi",
    "Kadının Statüsü Genel Müdürlüğü",
    "Kalkınma Bakanlığı",
    "Kamu Denetçiliği Kurumu",
    "Kamu Düzeni ve Güvenliği Müsteşarlığı",
    "Kamu Gözetimi Muhasebe ve Denetim Standartları Kurumu",
    "Kamu İhale Kurumu",
    "Kanserle Savaş Dairesi Başkanlığı",
    "Kanunlar Genel Müdürlüğü ",
    "Kara Kuvvetleri Komutanlığı",
    "Karamanoğlu Mehmetbey Üniversitesi",
    "Karayolları Genel Müdürlüğü",
    "Karayolu Düzenleme Genel Müdürlüğü",
    "Kırklareli Üniversitesi",
    "Kıyı Emniyeti Genel Müdürlüğü",
    "Kilis 7 Aralık Üniversitesi",
    "Konya Gıda ve Tarım Üniversitesi",
    "KTO Karatay Üniversitesi",
    "Küçük ve Orta Ölçekli İşletmeleri Geliştirme ve Destekleme İdaresi",
    "KOSGEB",
    "Kültür Varlıkları ve Müzeler Genel Müdürlüğü",
    "Kültür ve Turizm Bakanlığı",
    "Kültür ve Turizm Bakanlığı Araştırma ve Eğitim Genel Müdürlüğü",
    "Kültür ve Turizm Bakanlığı Döner Sermaye İşletmesi Merkez Müdürlüğü",
    "Kültür ve Turizm Bakanlığı Yatırım ve İşletmeler Genel Müdürlüğü",
    "Kütüphaneler ve Yayımlar Genel Müdürlüğü",
    "Maden İşleri Genel Müdürlüğü",
    "Maden Tetkik ve Arama Genel Müdürlüğü",
    "Mahalli İdareler Genel Müdürlüğü",
    "Makina ve Kimya Endüstrisi Kurumu",
    "Mali Suçları Araştırma Kurulu Başkanlığı",
    "Maliye Bakanlığı",
    "Mardin Artuklu Üniversitesi",
    "Mekansal Planlama Genel Müdürlüğü",
    "Merkezi Kayıt Kuruluşu A.Ş.",
    "Mesleki Hizmetler Genel Müdürlüğü",
    "Meslekî ve Teknik Eğitim Genel Müdürlüğü",
    "Mesleki Yeterlilik Kurumu",
    "Meteoroloji Genel Müdürlüğü",
    "Mevzuatı Geliştirme ve Yayın Genel Müdürlüğü",
    "Millenicom",
    "Milli Eğitim Bakanlığı",
    "Milli Emlak Genel Müdürlüğü",
    "Milli Güvenlik Kurulu Genel Sekreterliği",
    "Milli İstihbarat Teşkilatı Müsteşarlığı",
    "Milli Kütüphane Başkanlığı",
    "Milli Piyango İdaresi Genel Müdürlüğü",
    "Millî Savunma Bakanlığı",
    "Milli Savunma Bakanlığı Seferberlik Dairesi Başkanlığı",
    "Muhasebat Genel Müdürlüğü",
    "Necmettin Erbakan Üniversitesi",
    "nic.tr",
    "Nüfus ve Vatandaşlık İşleri Genel Müdürlüğü",
    "Okul İçi Beden Eğitimi Spor ve İzcilik Daire Başkanlığı",
    "Orman Genel Müdürlüğü",
    "Orman ve Su İşleri Bakanlığı",
    "Orta Anadolu İhracatçı Birlikleri Genel Sekreterliği",
    "Ortaöğretim Genel Müdürlüğü",
    "Osmaniye Korkut Ata Üniversitesi",
    "Öğretmen Yetiştirme ve Geliştirme Genel Müdürlüğü",
    "Ölçme, Seçme ve Yerleştirme Merkezi",
    "ÖSYM",
    "Ölçüler ve Standartlar Genel Müdürlüğü ",
    "Ömer Halisdemir Üniversitesi",
    "Özel Eğitim ve Rehberlik Hizmetleri Genel Müdürlüğü",
    "Özelleştirme İdaresi Başkanlığı",
    "Özel Öğretim Kurumları Genel Müdürlüğü",
    "Petrol İşleri Genel Müdürlüğü",
    "Polis Akademisi Başkanlığı",
    "PTT",
    "Radyo ve Televizyon Üst Kurulu",
    "Refik Saydam Hıfzısıhha Merkezi Başkanlığı",
    "Rekabet Kurumu",
    "Sağlık Bakanlığı",
    "Sağlık Bakanlığı Hudut ve Sahiller Sağlık Genel Müdürlüğü",
    "Sağlık Bakanlığı Personel Genel Müdürlüğü",
    "Sahil Güvenlik Komutanlığı",
    "Sanayi Bölgeleri Genel Müdürlüğü",
    "Sanayi Genel Müdürlüğü",
    "Savunma Sanayii ve Teknoloji Eğitim Merkezi",
    "SATEM"
    "Savunma Sanayi Müsteşarlığı",
    "STM",
    "Sayıştay",
    "Sermaye Piyasası Kurulu",
    "Sıtma Savaş Dairesi Başkanlığı",
    "Sigorta Bilgi ve Gözetim Merkezi",
    "Sinema Genel Müdürlüğü",
    "Sinop Üniversitesi",
    "Sivil Havacılık Genel Müdürlüğü",
    "Sosyal Güvenlik Kurumu",
    "Sosyal Yardımlar Genel Müdürlüğü",
    "Spor Genel Müdürlüğü",
    "Su Yönetimi Genel Müdürlüğü",
    "Sümer Halıcılık ve El Sanatları Sanayi ve Ticaret A.Ş.",
    "Şeker Kurumu",
    "Tabiat Varlıklarını Koruma Genel Müdürlüğü",
    "Takasbank",
    "Talim ve Terbiye Kurulu Başkanlığı",
    "Tanıtma Fonu Kurulu",
    "Tanıtma Genel Müdürlüğü",
    "Tapu ve Kadastro Genel Müdürlüğü",
    "Tarım İşletmeleri Genel Müdürlüğü",
    "Tarım Reformu Genel Müdürlüğü",
    "Tarımsal Araştırmalar ve Politikalar Genel Müdürlüğü",
    "Tarımsal Ekonomi ve Politika Geliştirme Enstitüsü",
    "Tarım Sigortaları Havuzu",
    "Tarım ve Kırsal Kalkınmayı Destekleme Kurumu Başkanlığı",
    "Tasarruf Mevduatı Sigorta Fonu Başkanlığı",
    "TBMM",
    "TCDD",
    "T.C. Mehmet Akif Ersoy Üniversitesi",
    "Telif Hakları Genel Müdürlüğü",
    "Temel Eğitim Genel Müdürlüğü",
    "Toplu Konut İdaresi Başkanlığı",
    "TOKİ",
    "Toprak Mahsulleri Ofisi",
    "TRT",
    "Tüketicinin Korunması ve Piyasa Gözetimi Genel Müdürlüğü",
    "Türk Akreditasyon Kurumu",
    "Türk-Alman Üniversitesi",
    "Türk Dil Kurumu",
    "Türk İşbirliği ve Koordinasyon Ajansı Başkanlığı",
    "Türkiye Adalet Akademisi Başkanlığı",
    "Türkiye Atom Enerjisi Kurumu Başkanlığı",
    "Türkiye Bankalar Birliği",
    "Türkiye Bilimler Akademisi",
    "TÜBA",
    "Türkiye Bilimsel ve Teknolojik Araştırma Kurumu",
    "TÜBİTAK",
    "Türkiye Cumhuriyet Merkez Bankası",
    "Türkiye Demiryolu Makinaları Sanayii",
    "TÜDEMSAŞ"
    "Türkiye Elektrik Dağıtım A.Ş.",
    "Türkiye Elektrik İletim A.Ş.",
    "TEİAŞ",
    "Türkiye Elektrik Ticaret ve Taahhüt A.Ş.",
    "TETAŞ",
    "Türkiye Elektromekanik Sanayii A.Ş. Genel Müdürlüğü",
    "Eximbank",
    "Türkiye İstatistik Kurumu Başkanlığı",
    "TÜİK",
    "Türkiye Kalkınma Bankası A.Ş. Genel Müdürlüğü",
    "Türkiye Kömür İşletmeleri Kurumu Genel Müdürlüğü",
    "Türkiye Lokomotif ve Motor Sanayii A.Ş. (TÜLOMSAŞ)",
    "Türkiye Muhasebe Standartları Kurulu",
    "Türkiye Odalar ve Borsalar Birliği",
    "TOBB",
    "Türkiye Petrolleri Anonim Ortaklığı Genel Müdürlüğü",
    "Türkiye Şeker Fabrikaları A. Ş.",
    "Türkiye Tarım Kredi Kooperatifleri Birliği",
    "Türkiye Taşkömürü Kurumu Genel Müdürlüğü",
    "Türkiye Ulusal Ajansı",
    "Türkiye Vagon Sanayii A.Ş. (TÜVASAŞ)",
    "Türkiye ve Orta Doğu Amme İdaresi Enstitüsü (TODAİE)",
    "Türkiye Yatırım Destek ve Tanıtım Ajansı Başkanlığı", 
    "Türk Patent ve Marka Kurumu",
    "Türk Standardları Enstitüsü",
    "Türk Tarih Kurumu",
    "Tütün ve Alkol Piyasası Düzenleme Kurumu",
    "Ulaştırma, Denizcilik ve Haberleşme Bakanlığı",
    "Ulusal Bor Araştırma Enstitüsü Başkanlığı",
    "Uşak Üniversitesi",
    "Üsküdar Üniversitesi",
    "Vakıflar Genel Müdürlüğü",
    "Vergi Denetim Kurulu Başkanlığı",
    "Verimlilik Genel Müdürlüğü",
    "Yapı İşleri Genel Müdürlüğü",
    "Yargıtay",
    "Yenilik ve Eğitim Teknolojileri Genel Müdürlüğü",
    "Yıldırım Beyazıt Üniversitesi",
    "Yurt Dışı Türkler ve Akraba Topluluklar Başkanlığı",
    "Yüksek Öğrenim Kredi ve Yurtlar Kurumu Genel Müdürlüğü",
    "Yükseköğretim Kurulu Başkanlığı",
    "YÖK",
    "Yüksek Seçim Kurulu Başkanlığı"
    "YSK",
    }

####### Step 1 Configurations ###########################################
STEP_1_QUERY = {"anonymous",
                "sayfa açılmıyor", 
                "bigisayar korsanı",
                "bilgisayar korsanları",
                "brute force attack",
                "brute force saldırısı",
                "casus yazılım",
                "clone phishing",
                "cross-site scripting", 
                "cross site scripting",
                "credential reuse",
                "cyber",
                "cyberattack",
                "cyberwarfare",
                "çöktü",
                "down olmuş",
                "denial-of-service",
                "dictionary attack",
                "dictionary saldırısı",
                "dos",
                "ddos",
                "kullanıcı hesapları ele geçirildi",
                "kimlik avı",
                "erişilemiyor",
                "erişim güçlüğü",
                "erişmekte güçlük",
                "erişim sağlanamıyor",
                "erişim problemi",
                "firewall",
                "fidye yazılımı",
                "forensics",
                "güvenlik duvarı",
                "hack",
                "hacklendi",
                "hacker",
                "istihbarat",
                "link spoofing",
                "malware",
                "man-in-the-middle",
                "mitm",
                "virüs bulaştı",
                "virüs çıkıyor",
                "oltalama",
                "oturum çalma",
                "phising",
                "ransomware",
                "rainbow attack",
                "rainbow saldırısı",
                "sayfa açılmıyor",
                "saldırı",
                "session hijacking",
                "spear-phishing",
                "spear phishing",
                "sql injection attack",
                "sql injection saldırısı",
                "sızma",
                "sızmış",
                "sızıntı",
                "sistem açığı",
                "siber",
                "ulaşılamıyor",
                "unreachable",
                "whaling",
                "website spoofing",
                "yemleme",
                "xss",
                "zafiyet",
                "zararlı yazılım"
 }

securityTermsList = STEP_1_QUERY.split (",")

####### Logger Related Codes #############################################
# create logger
logger = logging.getLogger('Logger')
logger.setLevel(logging.DEBUG)

# create console handler and set level to debug
ch = logging.StreamHandler()
ch.setLevel(logging.DEBUG)

# create formatter
formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')

# add formatter to ch
ch.setFormatter(formatter)

# add ch to logger
logger.addHandler(ch)
